In [1]:
import pandas as pd

# Загружаем данные
file_path = "cars.csv"
df = pd.read_csv(file_path)

In [2]:
from scipy import stats
from statsmodels import stats

In [3]:
df['Brand'] = df['CarName'].str.split().str[0]

In [4]:
# Подсчёт уникальных брендов
unique_brands_count = df['Brand'].nunique()

# Вывод результата
print(f"Количество уникальных брендов: {unique_brands_count}")

Количество уникальных брендов: 28

In [5]:
print("Список уникальных брендов:")
print(df['Brand'].unique())

Список уникальных брендов:
['alfa-romero' 'audi' 'bmw' 'chevrolet' 'dodge' 'honda' 'isuzu' 'jaguar'
 'maxda' 'mazda' 'buick' 'mercury' 'mitsubishi' 'Nissan' 'nissan'
 'peugeot' 'plymouth' 'porsche' 'porcshce' 'renault' 'saab' 'subaru'
 'toyota' 'toyouta' 'vokswagen' 'volkswagen' 'vw' 'volvo']

In [6]:
corrections = {
    "maxda": "mazda",
    "vokswagen": "volkswagen",
    "porcshce": "porsche",
    "toyouta": "toyota",
    "vw": "volkswagen"}
df["Brand"] = df["Brand"].replace(corrections)
df["Brand"] = df["Brand"].str.capitalize()
# Проверка уникальных значений
print("Уникальные бренды после исправлений:")
print(df["Brand"].unique())

Уникальные бренды после исправлений:
['Alfa-romero' 'Audi' 'Bmw' 'Chevrolet' 'Dodge' 'Honda' 'Isuzu' 'Jaguar'
 'Mazda' 'Buick' 'Mercury' 'Mitsubishi' 'Nissan' 'Peugeot' 'Plymouth'
 'Porsche' 'Renault' 'Saab' 'Subaru' 'Toyota' 'Volkswagen' 'Volvo']

In [7]:
# Количество уникальных значений
print(f"Количество уникальных брендов: {df['Brand'].nunique()}")

Количество уникальных брендов: 22

In [8]:
# Преобразование категориальных переменных в фиктивные
df_encoded = pd.get_dummies(df, columns=["Brand", "fueltype", "aspiration", "carbody", "drivewheel", "enginetype", "cylindernumber"])
X = df_encoded.drop("price", axis=1)
y = df_encoded["price"]

In [12]:
selected_columns = [
    'Brand', 'fueltype', 'aspiration', 'carbody', 'drivewheel', 
    'wheelbase', 'carlength', 'carwidth', 'curbweight', 
    'enginetype', 'cylindernumber', 'enginesize', 'boreratio', 
    'horsepower', 'price'
]

In [14]:
# Создаем корреляционную матрицу
correlation_matrix = df[selected_columns].corr()

In [15]:
correlation_matrix

,wheelbase,carlength,carwidth,curbweight,enginesize,boreratio,horsepower,price
wheelbase,1.000000,0.874587,0.795144,0.776386,0.569329,0.488750,0.353294,0.577816
carlength,0.874587,1.000000,0.841118,0.877728,0.683360,0.606454,0.552623,0.682920
carwidth,0.795144,0.841118,1.000000,0.867032,0.735433,0.559150,0.640732,0.759325
curbweight,0.776386,0.877728,0.867032,1.000000,0.850594,0.648480,0.750739,0.835305
enginesize,0.569329,0.683360,0.735433,0.850594,1.000000,0.583774,0.809769,0.874145
boreratio,0.488750,0.606454,0.559150,0.648480,0.583774,1.000000,0.573677,0.553173
horsepower,0.353294,0.552623,0.640732,0.750739,0.809769,0.573677,1.000000,0.808139
price,0.577816,0.682920,0.759325,0.835305,0.874145,0.553173,0.808139,1.000000

In [20]:
df_encoded = pd.get_dummies(df, columns=[
    'Brand', 'fueltype', 'aspiration', 'carbody', 
    'drivewheel', 'enginetype', 'cylindernumber'
], drop_first = True)

In [21]:
# Выбираем все числовые колонки (включая закодированные)
numeric_columns = df_encoded.select_dtypes(include=['number']).columns.tolist()

In [22]:
# Создаем корреляционную матрицу
correlation_matrix = df_encoded[numeric_columns].corr()

In [23]:
correlation_matrix

,car_ID,symboling,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,...,enginetype_ohc,enginetype_ohcf,enginetype_ohcv,enginetype_rotor,cylindernumber_five,cylindernumber_four,cylindernumber_six,cylindernumber_three,cylindernumber_twelve,cylindernumber_two
car_ID,1.000000,-0.151621,0.129729,0.170636,0.052387,0.255960,0.071962,-0.033930,0.260064,-0.160824,...,-0.087575,0.181374,-0.054794,-0.108464,-0.226065,0.230587,-0.035638,-0.099382,-0.062705,-0.108464
symboling,-0.151621,1.000000,-0.531954,-0.357612,-0.232919,-0.541038,-0.227691,-0.105790,-0.130051,-0.008735,...,-0.082855,0.037513,-0.013597,0.245950,-0.090188,-0.034161,-0.000238,0.065707,-0.047012,0.245950
wheelbase,0.129729,-0.531954,1.000000,0.874587,0.795144,0.589435,0.776386,0.569329,0.488750,0.160959,...,-0.204037,-0.183195,0.166152,-0.081174,0.261182,-0.309492,0.145842,-0.120709,0.037803,-0.081174
carlength,0.170636,-0.357612,0.874587,1.000000,0.841118,0.491029,0.877728,0.683360,0.606454,0.129533,...,-0.274413,-0.118320,0.244053,-0.057877,0.259894,-0.400210,0.262981,-0.187445,0.100413,-0.057877
carwidth,0.052387,-0.232919,0.795144,0.841118,1.000000,0.279210,0.867032,0.735433,0.559150,0.182942,...,-0.286211,-0.124446,0.348869,-0.013699,0.397690,-0.523135,0.209246,-0.183473,0.153516,-0.013699
carheight,0.255960,-0.541038,0.589435,0.491029,0.279210,1.000000,0.295572,0.067149,0.171071,-0.055307,...,0.036260,-0.046670,-0.065063,-0.238720,0.152982,0.059696,-0.049777,-0.015076,-0.170181,-0.238720
curbweight,0.071962,-0.227691,0.776386,0.877728,0.867032,0.295572,1.000000,0.850594,0.648480,0.168790,...,-0.413293,-0.080295,0.400878,-0.039196,0.264554,-0.576463,0.405490,-0.143903,0.187964,-0.039196
enginesize,-0.033930,-0.105790,0.569329,0.683360,0.735433,0.067149,0.850594,1.000000,0.583774,0.203129,...,-0.363334,-0.016508,0.562403,-0.184762,0.144878,-0.631431,0.511783,-0.111081,0.335555,-0.184762
boreratio,0.260064,-0.130051,0.488750,0.606454,0.559150,0.171071,0.648480,0.583774,1.000000,-0.055909,...,-0.410383,0.326798,0.119509,0.000127,-0.007797,-0.164076,0.128365,-0.108774,0.054482,0.000127
stroke,-0.160824,-0.008735,0.160959,0.129533,0.182942,-0.055307,0.168790,0.203129,-0.055909,1.000000,...,0.366084,-0.522808,-0.044813,-0.000187,0.176485,-0.111046,0.068388,-0.050450,-0.110878,-0.000187
compressionratio,0.150276,-0.178515,0.249786,0.158414,0.181129,0.261214,0.151362,0.028971,0.005197,0.186110,...,0.027545,-0.084328,-0.086649,-0.026436,0.173360,-0.012522,-0.065559,-0.011354,0.023986,-0.026436
horsepower,-0.015006,0.070873,0.353294,0.552623,0.640732,-0.108802,0.750739,0.809769,0.573677,0.080940,...,-0.427616,0.044752,0.431539,0.019250,0.110692,-0.639552,0.533544,-0.099600,0.280220,0.019250
peakrpm,-0.203789,0.273606,-0.360469,-0.287242,-0.220012,-0.320411,-0.266243,-0.244660,-0.254976,-0.067964,...,0.028189,-0.073885,-0.060011,0.259380,-0.021671,-0.047782,0.014256,-0.003697,-0.018411,0.259380
citympg,0.015940,-0.035823,-0.470414,-0.670909,-0.642704,-0.048640,-0.757414,-0.653658,-0.584532,-0.042145,...,0.391236,-0.032413,-0.336926,-0.183076,-0.207029,0.541267,-0.386551,0.233665,-0.131093,-0.183076
highwaympg,0.011255,0.034606,-0.544082,-0.704662,-0.677218,-0.107358,-0.797465,-0.677470,-0.587012,-0.043931,...,0.426049,-0.047086,-0.360616,-0.159173,-0.237167,0.547326,-0.366696,0.226756,-0.140150,-0.159173
price,-0.109093,-0.079978,0.577816,0.682920,0.759325,0.119336,0.835305,0.874145,0.553173,0.079443,...,-0.344270,0.016285,0.385991,-0.004544,0.249606,-0.697762,0.474978,-0.071388,0.199634,-0.004544
Brand_Audi,-0.305021,0.068348,0.110017,0.149405,0.246588,0.054281,0.088743,0.017231,-0.109189,0.086902,...,0.116687,-0.052831,-0.048926,-0.026525,0.670425,-0.285185,-0.068467,-0.013164,-0.013164,-0.026525
Brand_Bmw,-0.301368,-0.074482,0.147804,0.171120,0.053412,0.090949,0.145028,0.193885,0.107399,-0.056632,...,0.125060,-0.056621,-0.052436,-0.028428,-0.047985,-0.253894,0.396711,-0.014109,-0.014109,-0.028428
Brand_Buick,-0.107267,-0.135313,0.408210,0.347345,0.485409,0.165354,0.442556,0.483128,0.205292,0.114073,...,-0.099829,-0.056621,0.361005,-0.028428,0.399150,-0.374655,-0.073380,-0.014109,-0.014109,-0.028428
Brand_Chevrolet,-0.170925,0.016270,-0.127605,-0.218994,-0.194068,-0.066238,-0.187364,-0.136632,-0.153248,-0.067036,...,-0.015037,-0.034242,-0.031711,-0.017192,-0.029019,-0.031824,-0.044376,0.574513,-0.008532,-0.017192
Brand_Dodge,-0.278821,0.028609,-0.133609,-0.227400,-0.174349,-0.182891,-0.166769,-0.125043,-0.186629,0.075445,...,0.132984,-0.060209,-0.055759,-0.030229,-0.051026,0.115259,-0.078030,-0.015003,-0.015003,-0.030229
Brand_Honda,-0.290206,-0.045822,-0.191713,-0.280778,-0.185212,-0.051925,-0.229843,-0.172881,-0.296839,0.172091,...,0.161483,-0.073112,-0.067708,-0.036707,-0.061961,0.139959,-0.094752,-0.018218,-0.018218,-0.036707
Brand_Isuzu,-0.137070,-0.009555,-0.092329,-0.117767,-0.155429,-0.086803,-0.092904,-0.082885,-0.067749,-0.038517,...,0.087546,-0.039637,-0.036707,-0.019900,-0.033591,0.075877,-0.051369,-0.009877,-0.009877,-0.019900
Brand_Jaguar,-0.111204,-0.081830,0.214573,0.226930,0.229246,-0.129565,0.345315,0.451076,0.121894,0.173193,...,-0.196371,-0.034242,0.134974,-0.017192,-0.029019,-0.226571,0.208322,-0.008532,0.574513,-0.017192
Brand_Mazda,-0.223584,0.068625,-0.087050,-0.079248,-0.044906,-0.045158,-0.149218,-0.173061,-0.036392,0.032114,...,0.028696,-0.084492,-0.078247,0.469123,-0.071605,-0.007860,-0.109499,-0.021054,-0.021054,0.469123
Brand_Mercury,-0.031944,0.009347,0.045962,0.024751,0.068451,0.030881,0.047776,0.022067,0.116674,-0.030307,...,0.043450,-0.019672,-0.018218,-0.009877,-0.016672,0.037659,-0.025495,-0.004902,-0.004902,-0.009877
Brand_Mitsubishi,-0.087941,0.211978,-0.147396,-0.127248,-0.079518,-0.323726,-0.086990,-0.053867,-0.076071,0.198324,...,0.161483,-0.073112,-0.067708,-0.036707,-0.061961,0.139959,-0.094752,-0.018218,-0.018218,-0.036707
Brand_Nissan,-0.023592,0.041422,-0.156719,-0.077149,-0.118727,-0.011652,-0.092690,0.007331,-0.086481,0.057441,...,-0.038283,-0.087173,0.343621,-0.043767,-0.073877,-0.081020,0.208690,-0.021722,-0.021722,-0.043767
Brand_Peugeot,0.040238,-0.159891,0.453616,0.330602,0.276302,0.337701,0.305064,0.051079,0.222951,-0.072627,...,-0.383697,-0.066906,-0.061961,-0.033591,-0.056701,0.128078,-0.086709,-0.016672,-0.016672,-0.033591
Brand_Plymouth,0.060369,0.025103,-0.105511,-0.139780,-0.143778,-0.135256,-0.121164,-0.093339,-0.144979,0.072305,...,0.116687,-0.052831,-0.048926,-0.026525,-0.044773,0.101134,-0.068467,-0.013164,-0.013164,-0.026525
Brand_Porsche,0.066796,0.224755,-0.170472,-0.048682,0.089564,-0.170265,0.102171,0.229487,0.286897,-0.137181,...,-0.184198,0.319868,-0.041143,-0.022305,-0.037650,-0.218160,0.237498,-0.011070,-0.011070,-0.022305
Brand_Renault,0.047803,0.013252,-0.043896,0.041138,0.029787,-0.035625,-0.006892,0.012168,0.047848,0.204521,...,0.061599,-0.027889,-0.025828,-0.014002,-0.023635,0.053388,-0.036144,-0.006949,-0.006949,-0.014002
Brand_Saab,0.095362,0.232847,0.009927,0.177076,0.048052,0.169192,0.063495,-0.024692,0.028006,-0.195426,...,-0.021426,-0.048789,-0.045182,-0.024495,-0.041347,0.093396,-0.063229,-0.012157,-0.012157,-0.024495
Brand_Subaru,0.174865,-0.067071,-0.107161,-0.105172,-0.111605,0.002570,-0.114888,-0.118994,0.267866,-0.509133,...,-0.401796,0.887448,-0.064883,-0.035176,-0.059376,0.134120,-0.090798,-0.017458,-0.017458,-0.035176
Brand_Toyota,0.461496,-0.094046,-0.046785,-0.073906,-0.164234,-0.000530,-0.094786,-0.083807,-0.079203,-0.000570,...,0.086920,-0.120843,-0.111911,-0.060671,-0.102411,0.102464,0.010604,-0.030112,-0.030112,-0.060671
Brand_Volkswagen,0.360263,0.167106,-0.047664,-0.030714,-0.033924,0.149194,-0.101966,-0.117994,-0.184355,0.115246,...,0.154746,-0.070062,-0.064883,-0.035176,0.032836,0.084311,-0.090798,-0.017458,-0.017458,-0.035176
Brand_Volvo,0.390310,-0.403849,0.306228,0.285398,0.228758,0.245342,0.221127,0.088077,0.293458,-0.082315,...,0.099460,-0.066906,0.026864,-0.033591,-0.056701,0.024299,0.047952,-0.016672,-0.016672,-0.033591
fueltype_gas,-0.125568,0.194311,-0.308346,-0.212679,-0.233880,-0.284631,-0.217275,-0.069594,-0.054451,-0.241829,...,-0.020584,0.092384,0.085556,0.046383,-0.213527,0.020184,0.068594,0.023020,0.023020,0.046383
aspiration_turbo,0.067729,-0.059866,0.257611,0.234539,0.300567,0.087311,0.324902,0.108217,0.212614,0.222982,...,-0.020162,-0.034450,-0.070070,-0.066203,0.225968,0.009195,-0.091987,-0.032857,-0.032857,-0.066203
carbody_hardtop,0.077896,0.168845,-0.008608,0.047292,0.066360,-0.072328,0.098956,0.239363,0.208089,0.043215,...,-0.043606,0.136835,0.050924,-0.028428,0.063799,-0.133132,0.083317,-0.014109,-0.014109,-0.028428
carbody_hatchback,-0.111425,0.435648,-0.386094,-0.436269,-0.222308,-0.477476,-0.287501,-0.216805,-0.227032,0.052316,...,0.056560,-0.083821,-0.018531,0.195907,-0.125816,0.066757,-0.070235,0.097231,-0.050416,0.195907
carbody_sedan,-0.014702,-0.378341,0.291086,0.269647,0.154637,0.235863,0.099425,0.088459,0.030517,0.035630,...,0.080571,-0.075994,-0.003522,-0.132390,0.080203,-0.034178,0.053544,-0.065706,0.074604,-0.132390
carbody_wagon,0.150387,-0.298243,0.210899,0.219683,0.060639,0.459148,0.164075,-0.027518,0.105719,-0.095084,...,-0.101439,0.124260,-0.035806,-0.052573,0.043564,0.057522,-0.042974,-0.026093,-0.026093,-0.052573
drivewheel_fwd,-0.101395,0.102839,-0.460355,-0.508714,-0.472116,-0.100273,-0.666039,-0.518391,-0.583087,0.124397,...,0.450078,-0.067697,-0.187288,-0.167615,-0.063230,0.425481,-0.340270,0.058926,-0.083189,-0.167615
drivewheel_rwd,0.081236,-0.076381,0.498830,0.538370,0.511149,0.039814,0.669987,0.565509,0.574105,-0.022325,...,-0.402779,-0.099320,0.214684,0.183789,-0.003498,-0.434461,0.380172,-0.053740,0.091216,0.183789
enginetype_dohcv,0.031944,0.009347,-0.004156,0.009391,0.209136,-0.092628,0.109243,0.128248,0.158136,-0.032545,...,-0.112818,-0.019672,-0.018218,-0.009877,-0.016672,-0.130168,-0.025495,-0.004902,-0.004902,-0.009877
enginetype_l,0.009129,-0.133979,0.399603,0.261715,0.210771,0.319687,0.250124,0.016063,0.181729,-0.084688,...,-0.401796,-0.070062,-0.064883,-0.035176,-0.059376,0.084311,-0.090798,0.280784,-0.017458,-0.035176
enginetype_ohc,-0.087575,-0.082855,-0.204037,-0.274413,-0.286211,0.036260,-0.413293,-0.363334,-0.410383,0.366084,...,1.000000,-0.452754,-0.419290,-0.227314,0.147775,0.396945,-0.349710,-0.112818,-0.112818,-0.227314
enginetype_ohcf,0.181374,0.037513,-0.183195,-0.118320,-0.124446,-0.046670,-0.080295,-0.016508,0.326798,-0.522808,...,-0.452754,1.000000,-0.073112,-0.039637,-0.066906,0.016427,0.072472,-0.019672,-0.019672,-0.039637
enginetype_ohcv,-0.054794,-0.013597,0.166152,0.244053,0.348869,-0.065063,0.400878,0.562403,0.119509,-0.044813,...,-0.419290,-0.073112,1.000000,-0.036707,-0.061961,-0.483772,0.403302,-0.018218,0.269069,-0.036707
enginetype_rotor,-0.108464,0.245950,-0.081174,-0.057877,-0.013699,-0.238720,-0.039196,-0.184762,0.000127,-0.000187,...,-0.227314,-0.039637,-0.036707,1.000000,-0.033591,-0.262272,-0.051369,-0.009877,-0.009877,1.000000
cylindernumber_five,-0.226065,-0.090188,0.261182,0.259894,0.397690,0.152982,0.264554,0.144878,-0.007797,0.176485,...,0.147775,-0.066906,-0.061961,-0.033591,1.000000,-0.442706,-0.086709,-0.016672,-0.016672,-0.033591
cylindernumber_four,0.230587,-0.034161,-0.309492,-0.400210,-0.523135,0.059696,-0.576463,-0.631431,-0.164076,-0.111046,...,0.396945,0.016427,-0.483772,-0.262272,-0.442706,1.000000,-0.676996,-0.130168,-0.130168,-0.262272
cylindernumber_six,-0.035638,-0.000238,0.145842,0.262981,0.209246,-0.049777,0.405490,0.511783,0.128365,0.068388,...,-0.349710,0.072472,0.403302,-0.051369,-0.086709,-0.676996,1.000000,-0.025495,-0.025495,-0.051369
cylindernumber_three,-0.099382,0.065707,-0.120709,-0.187445,-0.183473,-0.015076,-0.143903,-0.111081,-0.108774,-0.050450,...,-0.112818,-0.019672,-0.018218,-0.009877,-0.016672,-0.130168,-0.025495,1.000000,-0.004902,-0.009877
cylindernumber_twelve,-0.062705,-0.047012,0.037803,0.100413,0.153516,-0.170181,0.187964,0.335555,0.054482,-0.110878,...,-0.112818,-0.019672,0.269069,-0.009877,-0.016672,-0.130168,-0.025495,-0.004902,1.000000,-0.009877
cylindernumber_two,-0.108464,0.245950,-0.081174,-0.057877,-0.013699,-0.238720,-0.039196,-0.184762,0.000127,-0.000187,...,-0.227314,-0.039637,-0.036707,1.000000,-0.033591,-0.262272,-0.051369,-0.009877,-0.009877,1.000000

In [24]:
df_encoded

,car_ID,symboling,CarName,doornumber,enginelocation,wheelbase,carlength,carwidth,carheight,curbweight,...,enginetype_ohc,enginetype_ohcf,enginetype_ohcv,enginetype_rotor,cylindernumber_five,cylindernumber_four,cylindernumber_six,cylindernumber_three,cylindernumber_twelve,cylindernumber_two
0,1,3,alfa-romero giulia,two,front,88.6,168.8,64.1,48.8,2548,...,0,0,0,0,0,1,0,0,0,0
1,2,3,alfa-romero stelvio,two,front,88.6,168.8,64.1,48.8,2548,...,0,0,0,0,0,1,0,0,0,0
2,3,1,alfa-romero Quadrifoglio,two,front,94.5,171.2,65.5,52.4,2823,...,0,0,1,0,0,0,1,0,0,0
3,4,2,audi 100 ls,four,front,99.8,176.6,66.2,54.3,2337,...,1,0,0,0,0,1,0,0,0,0
4,5,2,audi 100ls,four,front,99.4,176.6,66.4,54.3,2824,...,1,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,volvo 145e (sw),four,front,109.1,188.8,68.9,55.5,2952,...,1,0,0,0,0,1,0,0,0,0
201,202,-1,volvo 144ea,four,front,109.1,188.8,68.8,55.5,3049,...,1,0,0,0,0,1,0,0,0,0
202,203,-1,volvo 244dl,four,front,109.1,188.8,68.9,55.5,3012,...,0,0,1,0,0,0,1,0,0,0
203,204,-1,volvo 246,four,front,109.1,188.8,68.9,55.5,3217,...,1,0,0,0,0,0,1,0,0,0
204,205,-1,volvo 264gl,four,front,109.1,188.8,68.9,55.5,3062,...,1,0,0,0,0,1,0,0,0,0

In [27]:
df_dummy = pd.get_dummies(data=df[['Brand', 'fueltype', 'aspiration', 'carbody', 'drivewheel', 
    'wheelbase', 'carlength', 'carwidth', 'curbweight', 
    'enginetype', 'cylindernumber', 'enginesize', 'boreratio', 
    'horsepower', 'price']], drop_first = True)

In [28]:
df_dummy

,wheelbase,carlength,carwidth,curbweight,enginesize,boreratio,horsepower,price,Brand_Audi,Brand_Bmw,...,enginetype_ohc,enginetype_ohcf,enginetype_ohcv,enginetype_rotor,cylindernumber_five,cylindernumber_four,cylindernumber_six,cylindernumber_three,cylindernumber_twelve,cylindernumber_two
0,88.6,168.8,64.1,2548,130,3.47,111,13495.0,0,0,...,0,0,0,0,0,1,0,0,0,0
1,88.6,168.8,64.1,2548,130,3.47,111,16500.0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,94.5,171.2,65.5,2823,152,2.68,154,16500.0,0,0,...,0,0,1,0,0,0,1,0,0,0
3,99.8,176.6,66.2,2337,109,3.19,102,13950.0,1,0,...,1,0,0,0,0,1,0,0,0,0
4,99.4,176.6,66.4,2824,136,3.19,115,17450.0,1,0,...,1,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,109.1,188.8,68.9,2952,141,3.78,114,16845.0,0,0,...,1,0,0,0,0,1,0,0,0,0
201,109.1,188.8,68.8,3049,141,3.78,160,19045.0,0,0,...,1,0,0,0,0,1,0,0,0,0
202,109.1,188.8,68.9,3012,173,3.58,134,21485.0,0,0,...,0,0,1,0,0,0,1,0,0,0
203,109.1,188.8,68.9,3217,145,3.01,106,22470.0,0,0,...,1,0,0,0,0,0,1,0,0,0
204,109.1,188.8,68.9,3062,141,3.78,114,22625.0,0,0,...,1,0,0,0,0,1,0,0,0,0

In [34]:
import statsmodels.formula.api as smf

In [38]:
smf.ols(formula="price ~ horsepower", data = df_dummy).fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.653
Model:                            OLS   Adj. R-squared:                  0.651
Method:                 Least Squares   F-statistic:                     382.2
Date:                Mon, 17 Mar 2025   Prob (F-statistic):           1.48e-48
Time:                        21:00:27   Log-Likelihood:                -2024.0
No. Observations:                 205   AIC:                             4052.
Df Residuals:                     203   BIC:                             4059.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept  -3721.7615    929.849     -4.003      0.000   -5555.163   -1888.360
horsepower   163.2631      8.351     19.549      0.000     146.796     179.730
==============================================================================
Omnibus:                       47.741   Durbin-Watson:                   0.792
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               91.702
Skew:                           1.141   Prob(JB):                     1.22e-20
Kurtosis:                       5.352   Cond. No.                         314.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [46]:
# Определяем зависимую переменную (y)
y = df_dummy['price']

# Определяем независимые переменные (X), исключая 'price'
X = df_dummy.drop(columns=['price'])

# Добавляем константу (intercept)
X = sm.add_constant(X)

# Строим и обучаем модель
sm.OLS(y, X).fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.959
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     81.09
Date:                Mon, 17 Mar 2025   Prob (F-statistic):           4.86e-89
Time:                        21:21:44   Log-Likelihood:                -1804.2
No. Observations:                 205   AIC:                             3702.
Df Residuals:                     158   BIC:                             3858.
Df Model:                          46
Covariance Type:            nonrobust
=========================================================================================
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
const                 -3.472e+04   1.17e+04     -2.959      0.004   -5.79e+04   -1.15e+04
wheelbase               147.1396     76.234      1.930      0.055      -3.429     297.708
carlength              -113.2012     48.949     -2.313      0.022    -209.881     -16.522
carwidth                809.1860    214.508      3.772      0.000     385.514    1232.858
curbweight                4.1822      1.582      2.643      0.009       1.057       7.307
enginesize               61.4212     23.643      2.598      0.010      14.724     108.119
boreratio             -4319.4728   1759.825     -2.454      0.015   -7795.288    -843.657
horsepower               34.7010     18.000      1.928      0.056      -0.850      70.252
Brand_Audi              437.1040   2125.971      0.206      0.837   -3761.885    4636.093
Brand_Bmw              7993.4998   2105.132      3.797      0.000    3835.671    1.22e+04
Brand_Buick            3431.0969   2472.252      1.388      0.167   -1451.829    8314.023
Brand_Chevrolet       -2107.0167   2054.269     -1.026      0.307   -6164.387    1950.353
Brand_Dodge           -3034.5530   1686.337     -1.799      0.074   -6365.224     296.118
Brand_Honda           -2328.7396   1622.141     -1.436      0.153   -5532.617     875.138
Brand_Isuzu            -926.1643   1819.489     -0.509      0.611   -4519.823    2667.495
Brand_Jaguar           2695.2664   2546.268      1.059      0.291   -2333.847    7724.379
Brand_Mazda           -1291.5657   1652.561     -0.782      0.436   -4555.527    1972.395
Brand_Mercury         -2762.0259   2786.701     -0.991      0.323   -8266.016    2741.965
Brand_Mitsubishi      -3699.6473   1650.046     -2.242      0.026   -6958.640    -440.654
Brand_Nissan          -1488.1217   1563.564     -0.952      0.343   -4576.305    1600.061
Brand_Peugeot         -2671.4595   1795.328     -1.488      0.139   -6217.398     874.479
Brand_Plymouth        -3052.1258   1670.829     -1.827      0.070   -6352.166     247.915
Brand_Porsche          4915.9715   2797.761      1.757      0.081    -609.864    1.04e+04
Brand_Renault         -2865.2197   2073.046     -1.382      0.169   -6959.676    1229.237
Brand_Saab              719.8222   1767.620      0.407      0.684   -2771.390    4211.035
Brand_Subaru          -1.164e+04   3416.221     -3.407      0.001   -1.84e+04   -4892.375
Brand_Toyota          -2608.7871   1539.320     -1.695      0.092   -5649.086     431.512
Brand_Volkswagen      -2261.9355   1606.886     -1.408      0.161   -5435.683     911.812
Brand_Volvo              68.2605   1943.170      0.035      0.972   -3769.679    3906.200
fueltype_gas           -243.7792    908.310     -0.268      0.789   -2037.774    1550.216
aspiration_turbo        596.6566    676.548      0.882      0.379    -739.588    1932.902
carbody_hardtop       -2556.7157   1213.929     -2.106      0.037   -4954.337    -159.094
carbody_hatchback     -3044.4196   1107.064     -2.750      0.007   -5230.972    -857.867
carbody_sedan         -2256.9173   1154.971     -1.954      0.052   -4538.090      24.256
carbody_wagon         -2815.4970   1223.156     -2.302      0.023   -5231.343    -399.651
drivewheel_fwd         -169.4926    888.585     -0.191      0.849   -1924.531    1585.545
drivewheel_rwd          231.9066   1039.685      0.223      0.824   -1821.566    2285.380
enginetype_dohcv      -8358.0756   4326.239     -1.932      0.055   -1.69e+04     186.645
enginetype_l          -1067.3120   1602.125     -0.666      0.506   -4231.657    2097.033
enginetype_ohc         -273.7175   1063.557     -0.257      0.797   -2374.341    1826.906
enginetype_ohcf        1.031e+04   2672.508      3.857      0.000    5028.873    1.56e+04
enginetype_ohcv       -2393.8587   1214.631     -1.971      0.050   -4792.867       5.150
enginetype_rotor         37.4715   2092.597      0.018      0.986   -4095.600    4170.543
cylindernumber_five   -5235.5232   2887.214     -1.813      0.072   -1.09e+04     466.990
cylindernumber_four   -3741.3604   3542.130     -1.056      0.292   -1.07e+04    3254.673
cylindernumber_six    -5441.5317   2628.646     -2.070      0.040   -1.06e+04    -249.713
cylindernumber_three   1604.1476   2774.698      0.578      0.564   -3876.137    7084.432
cylindernumber_twelve -8097.1585   3616.336     -2.239      0.027   -1.52e+04    -954.561
cylindernumber_two       37.4715   2092.597      0.018      0.986   -4095.600    4170.543
==============================================================================
Omnibus:                       81.075   Durbin-Watson:                   1.382
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              487.187
Skew:                           1.379   Prob(JB):                    1.62e-106
Kurtosis:                      10.031   Cond. No.                     1.02e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.35e-23. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [47]:
columns_list = ', '.join(f'"{col}"' for col in df_dummy.columns)
print(f'[{columns_list}]')

["wheelbase", "carlength", "carwidth", "curbweight", "enginesize", "boreratio", "horsepower", "price", "Brand_Audi", "Brand_Bmw", "Brand_Buick", "Brand_Chevrolet", "Brand_Dodge", "Brand_Honda", "Brand_Isuzu", "Brand_Jaguar", "Brand_Mazda", "Brand_Mercury", "Brand_Mitsubishi", "Brand_Nissan", "Brand_Peugeot", "Brand_Plymouth", "Brand_Porsche", "Brand_Renault", "Brand_Saab", "Brand_Subaru", "Brand_Toyota", "Brand_Volkswagen", "Brand_Volvo", "fueltype_gas", "aspiration_turbo", "carbody_hardtop", "carbody_hatchback", "carbody_sedan", "carbody_wagon", "drivewheel_fwd", "drivewheel_rwd", "enginetype_dohcv", "enginetype_l", "enginetype_ohc", "enginetype_ohcf", "enginetype_ohcv", "enginetype_rotor", "cylindernumber_five", "cylindernumber_four", "cylindernumber_six", "cylindernumber_three", "cylindernumber_twelve", "cylindernumber_two"]

In [50]:
# Определяем зависимую переменную (y)
y = df_dummy['price']

# Определяем независимые переменные (X), исключая 'price'
X = df_dummy[["wheelbase", "carlength", "carwidth", "curbweight", "enginesize", "boreratio", "horsepower", "fueltype_gas", "aspiration_turbo", "carbody_hardtop", "carbody_hatchback", "carbody_sedan", "carbody_wagon", "drivewheel_fwd", "drivewheel_rwd", "enginetype_dohcv", "enginetype_l", "enginetype_ohc", "enginetype_ohcf", "enginetype_ohcv", "enginetype_rotor", "cylindernumber_five", "cylindernumber_four", "cylindernumber_six", "cylindernumber_three", "cylindernumber_twelve", "cylindernumber_two"]]

# Добавляем константу (intercept)
X = sm.add_constant(X)

# Строим и обучаем модель
sm.OLS(y, X).fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.914
Model:                            OLS   Adj. R-squared:                  0.901
Method:                 Least Squares   F-statistic:                     72.32
Date:                Mon, 17 Mar 2025   Prob (F-statistic):           9.86e-81
Time:                        21:36:25   Log-Likelihood:                -1881.6
No. Observations:                 205   AIC:                             3817.
Df Residuals:                     178   BIC:                             3907.
Df Model:                          26
Covariance Type:            nonrobust
=========================================================================================
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
const                   -1.7e+04    1.3e+04     -1.309      0.192   -4.26e+04    8625.219
wheelbase                71.1868     87.028      0.818      0.414    -100.552     242.925
carlength               -51.3497     50.341     -1.020      0.309    -150.692      47.993
carwidth                541.8700    253.327      2.139      0.034      41.958    1041.782
curbweight                2.9577      1.796      1.647      0.101      -0.585       6.501
enginesize               36.0515     22.376      1.611      0.109      -8.105      80.208
boreratio             -2230.4519   1731.681     -1.288      0.199   -5647.719    1186.815
horsepower               86.8164     16.717      5.193      0.000      53.827     119.806
fueltype_gas          -2423.0935    975.579     -2.484      0.014   -4348.283    -497.904
aspiration_turbo      -1139.2334    787.230     -1.447      0.150   -2692.738     414.271
carbody_hardtop       -3728.0949   1519.366     -2.454      0.015   -6726.383    -729.807
carbody_hatchback     -4639.1279   1294.594     -3.583      0.000   -7193.855   -2084.401
carbody_sedan         -3337.7854   1356.075     -2.461      0.015   -6013.838    -661.732
carbody_wagon         -4315.4661   1465.089     -2.946      0.004   -7206.646   -1424.287
drivewheel_fwd          297.2402   1121.766      0.265      0.791   -1916.431    2510.912
drivewheel_rwd         1939.1594   1226.536      1.581      0.116    -481.263    4359.582
enginetype_dohcv      -1.713e+04   4540.120     -3.773      0.000   -2.61e+04   -8171.142
enginetype_l           2176.0521   1332.818      1.633      0.104    -454.106    4806.211
enginetype_ohc         4006.5687    897.437      4.464      0.000    2235.584    5777.553
enginetype_ohcf        5421.2822   1388.078      3.906      0.000    2682.076    8160.488
enginetype_ohcv       -5001.2242   1345.435     -3.717      0.000   -7656.280   -2346.169
enginetype_rotor      -5196.6413   2084.532     -2.493      0.014   -9310.217   -1083.066
cylindernumber_five   -1.389e+04   2891.599     -4.802      0.000   -1.96e+04   -8180.353
cylindernumber_four   -1.618e+04   3243.610     -4.989      0.000   -2.26e+04   -9780.800
cylindernumber_six    -1.175e+04   2287.516     -5.135      0.000   -1.63e+04   -7231.547
cylindernumber_three  -9264.0553   4750.899     -1.950      0.053   -1.86e+04     111.279
cylindernumber_twelve -1.214e+04   3386.507     -3.585      0.000   -1.88e+04   -5458.378
cylindernumber_two    -5196.6413   2084.532     -2.493      0.014   -9310.217   -1083.066
==============================================================================
Omnibus:                       18.493   Durbin-Watson:                   1.249
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               50.728
Skew:                           0.293   Prob(JB):                     9.65e-12
Kurtosis:                       5.365   Cond. No.                     1.02e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.35e-23. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [1]:
import numpy as np
from scipy.stats import chi2_contingency
obs = np.array([[21, 75, 5], [16, 60, 10]])
chi2_contingency(obs)

(2.8239706434502656,
 0.24365906101675808,
 2,
 array([[19.98395722, 72.9144385 ,  8.10160428],
        [17.01604278, 62.0855615 ,  6.89839572]]))